# Group Project: High tide in Venice

### Keusseoglou Haralambos, Kulka Federica, Moawad Simone, Scarpato Giovanni

In [1]:
#Importing relevant packages
import pandas as pd
import numpy as np

In [2]:
#Importing csv data
cavalli = pd.read_csv("data/Stazione_PalazzoCavalli.csv", sep=';', parse_dates =["Data"])
burano = pd.read_csv("data/Stazione_Burano.csv", sep=';', parse_dates =["Data"])
ismar1 = pd.read_csv("data/Stazione_Piattaforma.csv", sep=';', parse_dates =["Data"])
ismar2 = pd.read_csv("data/Stazione_Piattaforma_pg.csv", sep=';', parse_dates =["Data"])
san_giorgio = pd.read_csv("data/Stazione_SanGiorgio.csv", sep=';', parse_dates =["Data"])
miser = pd.read_csv("data/Stazione_Misericordia.csv", sep=';', parse_dates =["Data"])
salute = pd.read_csv("data/Stazione_PuntaSalute_CanalGrande.csv", sep=';', parse_dates =["Data"])
faro = pd.read_csv("data/Stazione_DigaSudLido.csv", sep=';', parse_dates =["Data"])
meteo = pd.read_csv("data/Dati_Meteo.csv", sep=';', parse_dates =["Data"])

#Importing json data
astro1 = pd.read_json("data/astronomical_tide_2022.json", convert_dates=['data'])
astro2 = pd.read_json("data/astronomical_tide_2023.json", convert_dates=['data'])

Below, the first five observations for each dataset are displayed in order to have a quick overview of the variables.\
More information on the data, including the units of measure, are present into the documentation of the project that you can find at the bottom of the notebook.

In [3]:
burano.head()

                 Data  Burano Liv.Idrom. medio 1m
0 2022-11-10 00:00:00                        0.66
1 2022-11-10 00:05:00                        0.67
2 2022-11-10 00:10:00                        0.67
3 2022-11-10 00:15:00                        0.67
4 2022-11-10 00:20:00                        0.67

In [4]:
ismar1.head()

,Data,Piattaforma CNR Liv.Idrom. medio 1m,Piattaforma CNR D.Vento med. 10m,Piattaforma CNR V.Vento med.10m,Piattaforma CNR V.Vento max,Piattaforma CNR Onda: Alt. sign.,Piattaforma CNR Onda: Alt. max,Piattaforma CNR Pressione,Piattaforma CNR Temperatura,Piattaforma CNR Temp. Acqua,Piattaforma CNR Umidita',Piattaforma CNR Radiazione solare,Piattaforma CNR Pioggia 5m
0,2022-11-10 00:00:00,0.64,31.0,6.0,7.2,0.28,0.51,1018.5,15.6,18.5,75.0,NaN,0.0
1,2022-11-10 00:05:00,0.63,34.0,6.3,7.0,0.28,0.51,1018.5,15.5,18.5,75.0,NaN,0.0
2,2022-11-10 00:10:00,0.63,32.0,6.6,7.6,0.28,0.51,1018.4,15.5,18.7,74.0,NaN,0.0
3,2022-11-10 00:15:00,0.62,36.0,6.8,7.1,0.26,0.47,1018.3,15.4,18.4,74.0,NaN,0.0
4,2022-11-10 00:20:00,0.61,35.0,6.8,7.8,0.26,0.47,1018.4,15.4,18.6,76.0,NaN,0.0

In [5]:
ismar2.head()

                 Data  Piattaforma CNR Pioggia 5m
0 2022-11-10 00:00:00                         0.0
1 2022-11-10 01:00:00                         0.0
2 2022-11-10 02:00:00                         0.0
3 2022-11-10 03:00:00                         0.0
4 2022-11-10 04:00:00                         0.0

In [6]:
san_giorgio.head()

,Data,San Giorgio D.Vento med. 10m,San Giorgio V.Vento med.10m,San Giorgio V.Vento max,San Giorgio Temperatura,San Giorgio Umidita',San Giorgio Radiazione solare
0,2022-11-10 00:00:00,18.0,4.0,4.9,14.0,79.0,0.0
1,2022-11-10 00:05:00,18.0,4.3,4.9,14.0,79.0,0.0
2,2022-11-10 00:10:00,22.0,4.5,5.2,14.0,79.0,0.0
3,2022-11-10 00:15:00,25.0,4.3,5.4,14.0,79.0,0.0
4,2022-11-10 00:20:00,23.0,4.6,5.2,13.9,79.0,0.0

In [7]:
miser.head()

,Data,Misericordia Liv.Idrom. medio 1m,Misericordia D.Vento med. 10m,Misericordia V.Vento med.10m,Misericordia V.Vento max,Misericordia Onda: Alt. sign.,Misericordia Onda: Alt. max
0,2022-11-10 00:00:00,0.71,12,3.0,3.8,0.14,0.20
1,2022-11-10 00:05:00,0.71,10,3.1,3.8,0.12,0.22
2,2022-11-10 00:10:00,0.71,13,3.2,3.9,0.10,0.18
3,2022-11-10 00:15:00,0.71,11,3.3,4.0,0.10,0.16
4,2022-11-10 00:20:00,0.71,29,3.3,3.8,0.10,0.18

In [8]:
salute.head()

                 Data  P. Salute Liv.Idrom. medio 1m  P. Salute Temp. Acqua
0 2022-08-10 00:00:00                           0.32                   26.9
1 2022-08-10 00:05:00                           0.30                   27.8
2 2022-08-10 00:10:00                           0.27                   27.9
3 2022-08-10 00:15:00                           0.26                   26.9
4 2022-08-10 00:20:00                           0.24                   27.8

In [9]:
faro.head()

,Data,D.S. Lido Liv.Idrom. medio 1m,Faro Diga Lido V.Vento med.10m,Faro Diga Lido V.Vento max,Faro Diga Lido D.Vento med. 10m
0,2022-11-10 00:00:00,0.65,3.8,4.5,23
1,2022-11-10 00:05:00,0.64,3.9,4.5,31
2,2022-11-10 00:10:00,0.64,3.6,4.3,33
3,2022-11-10 00:15:00,0.63,3.6,4.5,34
4,2022-11-10 00:20:00,0.62,3.7,4.3,38

In [10]:
meteo.head()

,Data,Palazzo Cavalli Pressione,Palazzo Cavalli Temperatura,Palazzo Cavalli Umidita',San Giorgio Radiazione solare,San Giorgio D.Vento med. 10m,San Giorgio V.Vento med.10m,San Giorgio V.Vento max,P. Salute Temp. Acqua
0,2022-11-10 00:00:00,1018.9,14.3,77.0,0.0,18.0,4.0,4.9,16.6
1,2022-11-10 00:05:00,1018.9,14.1,78.0,0.0,18.0,4.3,4.9,16.6
2,2022-11-10 00:10:00,1018.8,14.2,78.0,0.0,22.0,4.5,5.2,16.7
3,2022-11-10 00:15:00,1018.8,14.2,78.0,0.0,25.0,4.3,5.4,16.6
4,2022-11-10 00:20:00,1018.7,14.2,78.0,0.0,23.0,4.6,5.2,16.6

In [11]:
astro1.head()

                 data  valore
0 2022-01-01 00:00:00      45
1 2022-01-01 00:05:00      44
2 2022-01-01 00:10:00      43
3 2022-01-01 00:15:00      42
4 2022-01-01 00:20:00      42

In [12]:
astro2.head()

                 data  valore
0 2023-01-01 00:00:00      21
1 2023-01-01 00:05:00      22
2 2023-01-01 00:10:00      22
3 2023-01-01 00:15:00      22
4 2023-01-01 00:20:00      23

Astronomical tides data are divided in two datasets by year. For a better management of the datasets, we unify both datasets in a single one in which observations are chronologically ordered.

In [13]:
#Concat astro data
astro=pd.concat([astro1,astro2])
#Rename columns
astro=astro.rename(columns={"data":"Data"})

By the documentation provided by "Comune di Venezia", we understand that astronomical tides are measured in cm.\
Data about the observed sea level in all the other datasets are reported in metres.\
Therefore, we convert these observation in metres without any loss of significative figures.

In [14]:
#Converting astro data from cm to m
astro['valore']=astro['valore']/100
astro

                      Data  valore
0      2022-01-01 00:00:00    0.45
1      2022-01-01 00:05:00    0.44
2      2022-01-01 00:10:00    0.43
3      2022-01-01 00:15:00    0.42
4      2022-01-01 00:20:00    0.42
...                    ...     ...
105115 2023-12-31 23:35:00    0.38
105116 2023-12-31 23:40:00    0.39
105117 2023-12-31 23:45:00    0.40
105118 2023-12-31 23:50:00    0.41
105119 2023-12-31 23:55:00    0.42

[210240 rows x 2 columns]

We merge all the datasets into a single one.

In [15]:
#Merging data
from functools import reduce

dfs = [cavalli, burano, ismar1, ismar2, san_giorgio, miser, salute, faro, meteo, astro]
venice = reduce(lambda  left,right: pd.merge(left,right,on=['Data'],how='outer'), dfs).sort_values('Data').reset_index(drop=True)
venice

,Data,Palazzo Cavalli Pressione_x,Palazzo Cavalli Temperatura_x,Palazzo Cavalli Umidita'_x,Palazzo Cavalli Radiazione solare,Palazzo Cavalli Pioggia 5m,Burano Liv.Idrom. medio 1m,Piattaforma CNR Liv.Idrom. medio 1m,Piattaforma CNR D.Vento med. 10m,Piattaforma CNR V.Vento med.10m,...,Faro Diga Lido D.Vento med. 10m,Palazzo Cavalli Pressione_y,Palazzo Cavalli Temperatura_y,Palazzo Cavalli Umidita'_y,San Giorgio Radiazione solare_y,San Giorgio D.Vento med. 10m_y,San Giorgio V.Vento med.10m_y,San Giorgio V.Vento max_y,P. Salute Temp. Acqua_y,valore
0,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.45
1,2022-01-01 00:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.44
2,2022-01-01 00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.43
3,2022-01-01 00:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.42
4,2022-01-01 00:20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210235,2023-12-31 23:35:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.38
210236,2023-12-31 23:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.39
210237,2023-12-31 23:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.40
210238,2023-12-31 23:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.41
210239,2023-12-31 23:55:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.42

In [16]:
#Selecting relevant period of time
venice=venice.loc[(venice['Data']>='2022-11-15 00:00:00') & (venice['Data']<='2023-01-31 23:55:00')].reset_index(drop=True)

venice

,Data,Palazzo Cavalli Pressione_x,Palazzo Cavalli Temperatura_x,Palazzo Cavalli Umidita'_x,Palazzo Cavalli Radiazione solare,Palazzo Cavalli Pioggia 5m,Burano Liv.Idrom. medio 1m,Piattaforma CNR Liv.Idrom. medio 1m,Piattaforma CNR D.Vento med. 10m,Piattaforma CNR V.Vento med.10m,...,Faro Diga Lido D.Vento med. 10m,Palazzo Cavalli Pressione_y,Palazzo Cavalli Temperatura_y,Palazzo Cavalli Umidita'_y,San Giorgio Radiazione solare_y,San Giorgio D.Vento med. 10m_y,San Giorgio V.Vento med.10m_y,San Giorgio V.Vento max_y,P. Salute Temp. Acqua_y,valore
0,2022-11-15 00:00:00,1018.9,12.2,88.0,NaN,0.0,0.25,0.33,297.0,4.5,...,303.0,1018.9,12.2,88.0,NaN,291.0,1.8,2.6,15.5,0.21
1,2022-11-15 00:05:00,1018.8,12.2,88.0,NaN,0.0,0.26,0.34,297.0,4.6,...,307.0,1018.8,12.2,88.0,0.0,289.0,2.1,3.0,15.5,0.22
2,2022-11-15 00:10:00,1018.8,12.2,88.0,NaN,0.0,0.27,0.35,288.0,4.7,...,299.0,1018.8,12.2,88.0,0.0,286.0,1.7,2.5,15.5,0.22
3,2022-11-15 00:15:00,1018.8,12.2,88.0,NaN,0.0,0.27,0.35,284.0,4.8,...,290.0,1018.8,12.2,88.0,0.0,278.0,2.3,2.9,15.5,0.23
4,2022-11-15 00:20:00,1018.9,12.2,88.0,NaN,0.0,0.28,0.36,279.0,5.2,...,281.0,1018.9,12.2,88.0,0.0,260.0,2.4,3.3,15.5,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22459,2023-01-31 23:35:00,1020.4,4.8,89.0,0.0,0.0,0.36,0.32,321.0,3.7,...,30.0,1020.4,4.8,89.0,0.0,25.0,3.2,4.0,6.5,0.43
22460,2023-01-31 23:40:00,1020.4,4.6,89.0,NaN,0.0,0.36,0.32,334.0,3.7,...,32.0,1020.4,4.6,89.0,0.0,27.0,3.9,4.6,6.5,0.43
22461,2023-01-31 23:45:00,1020.2,4.5,90.0,0.0,0.0,0.35,0.32,330.0,3.4,...,35.0,1020.2,4.5,90.0,0.0,23.0,3.7,4.5,6.5,0.43
22462,2023-01-31 23:50:00,1020.3,4.5,90.0,0.0,0.0,0.35,0.31,331.0,3.2,...,36.0,1020.3,4.5,90.0,0.0,29.0,3.2,4.1,6.5,0.43
22463,2023-01-31 23:55:00,1020.3,4.6,90.0,0.0,0.0,0.34,0.31,352.0,3.2,...,44.0,1020.3,4.6,90.0,0.0,30.0,3.3,3.9,6.5,0.42

In [17]:
#Showing columns
venice.columns

Index(['Data', 'Palazzo Cavalli Pressione_x', 'Palazzo Cavalli Temperatura_x',
       'Palazzo Cavalli Umidita'_x', 'Palazzo Cavalli Radiazione solare',
       'Palazzo Cavalli Pioggia 5m', 'Burano Liv.Idrom. medio 1m',
       'Piattaforma CNR Liv.Idrom. medio 1m',
       'Piattaforma CNR D.Vento med. 10m', 'Piattaforma CNR V.Vento med.10m',
       'Piattaforma CNR V.Vento max', 'Piattaforma CNR Onda: Alt. sign.',
       'Piattaforma CNR Onda: Alt. max', 'Piattaforma CNR Pressione',
       'Piattaforma CNR Temperatura', 'Piattaforma CNR Temp. Acqua',
       'Piattaforma CNR Umidita'', 'Piattaforma CNR Radiazione solare',
       'Piattaforma CNR Pioggia 5m_x', 'Piattaforma CNR Pioggia 5m_y',
       'San Giorgio D.Vento med. 10m_x', 'San Giorgio V.Vento med.10m_x',
       'San Giorgio V.Vento max_x', 'San Giorgio Temperatura',
       'San Giorgio Umidita'', 'San Giorgio Radiazione solare_x',
       'Misericordia Liv.Idrom. medio 1m', 'Misericordia D.Vento med. 10m',
       'Misericordia V.Vento med.10m', 'Misericordia V.Vento max',
       'Misericordia Onda: Alt. sign.', 'Misericordia Onda: Alt. max',
       'P. Salute Liv.Idrom. medio 1m', 'P. Salute Temp. Acqua_x',
       'D.S. Lido Liv.Idrom. medio 1m', 'Faro Diga Lido V.Vento med.10m',
       'Faro Diga Lido V.Vento max', 'Faro Diga Lido D.Vento med. 10m',
       'Palazzo Cavalli Pressione_y', 'Palazzo Cavalli Temperatura_y',
       'Palazzo Cavalli Umidita'_y', 'San Giorgio Radiazione solare_y',
       'San Giorgio D.Vento med. 10m_y', 'San Giorgio V.Vento med.10m_y',
       'San Giorgio V.Vento max_y', 'P. Salute Temp. Acqua_y', 'valore'],
      dtype='object')

Columns from meteo dataset have the same name of columns from other datasets.\
We check if these columns contain the same observations.

In [18]:
venice['Palazzo Cavalli Pressione_x'].equals(venice['Palazzo Cavalli Pressione_y'])

True

In [19]:
venice["Palazzo Cavalli Umidita'_x"].equals(venice["Palazzo Cavalli Umidita'_y"])

True

In [20]:
venice['Palazzo Cavalli Temperatura_x'].equals(venice['Palazzo Cavalli Temperatura_y'])

True

In [21]:
venice['San Giorgio Radiazione solare_x'].equals(venice['San Giorgio Radiazione solare_y'])

True

In [22]:
venice['San Giorgio D.Vento med. 10m_x'].equals(venice['San Giorgio D.Vento med. 10m_y'])

True

In [23]:
venice['San Giorgio V.Vento med.10m_x'].equals(venice['San Giorgio V.Vento med.10m_y'])

True

In [24]:
venice['San Giorgio V.Vento max_x'].equals(venice['San Giorgio V.Vento max_y'])

True

In [25]:
venice['P. Salute Temp. Acqua_x'].equals(venice['P. Salute Temp. Acqua_y'])

True

Since the columns contain the same values, we drop the redundant columns, that are exactly the ones of meteo dataset.

In [26]:
venice=venice.drop(columns=['Palazzo Cavalli Pressione_y',"Palazzo Cavalli Umidita'_y",'Palazzo Cavalli Temperatura_y',
                    'San Giorgio Radiazione solare_y','San Giorgio D.Vento med. 10m_y','San Giorgio V.Vento med.10m_y',
                    'San Giorgio V.Vento max_y','P. Salute Temp. Acqua_y'])
venice

,Data,Palazzo Cavalli Pressione_x,Palazzo Cavalli Temperatura_x,Palazzo Cavalli Umidita'_x,Palazzo Cavalli Radiazione solare,Palazzo Cavalli Pioggia 5m,Burano Liv.Idrom. medio 1m,Piattaforma CNR Liv.Idrom. medio 1m,Piattaforma CNR D.Vento med. 10m,Piattaforma CNR V.Vento med.10m,...,Misericordia V.Vento max,Misericordia Onda: Alt. sign.,Misericordia Onda: Alt. max,P. Salute Liv.Idrom. medio 1m,P. Salute Temp. Acqua_x,D.S. Lido Liv.Idrom. medio 1m,Faro Diga Lido V.Vento med.10m,Faro Diga Lido V.Vento max,Faro Diga Lido D.Vento med. 10m,valore
0,2022-11-15 00:00:00,1018.9,12.2,88.0,NaN,0.0,0.25,0.33,297.0,4.5,...,2.3,0.10,0.20,0.30,15.5,0.36,2.6,3.0,303.0,0.21
1,2022-11-15 00:05:00,1018.8,12.2,88.0,NaN,0.0,0.26,0.34,297.0,4.6,...,2.5,0.06,0.13,0.31,15.5,0.37,2.7,3.1,307.0,0.22
2,2022-11-15 00:10:00,1018.8,12.2,88.0,NaN,0.0,0.27,0.35,288.0,4.7,...,2.6,0.05,0.09,0.31,15.5,0.37,2.9,3.3,299.0,0.22
3,2022-11-15 00:15:00,1018.8,12.2,88.0,NaN,0.0,0.27,0.35,284.0,4.8,...,2.5,0.04,0.06,0.32,15.5,0.38,2.9,3.1,290.0,0.23
4,2022-11-15 00:20:00,1018.9,12.2,88.0,NaN,0.0,0.28,0.36,279.0,5.2,...,2.7,0.05,0.13,0.33,15.5,0.40,2.7,3.2,281.0,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22459,2023-01-31 23:35:00,1020.4,4.8,89.0,0.0,0.0,0.36,0.32,321.0,3.7,...,2.6,0.07,0.20,0.33,6.5,0.31,3.2,3.3,30.0,0.43
22460,2023-01-31 23:40:00,1020.4,4.6,89.0,NaN,0.0,0.36,0.32,334.0,3.7,...,2.2,0.10,0.20,0.33,6.5,0.31,2.5,3.3,32.0,0.43
22461,2023-01-31 23:45:00,1020.2,4.5,90.0,0.0,0.0,0.35,0.32,330.0,3.4,...,2.3,0.08,0.23,0.31,6.5,0.31,2.6,3.3,35.0,0.43
22462,2023-01-31 23:50:00,1020.3,4.5,90.0,0.0,0.0,0.35,0.31,331.0,3.2,...,2.0,0.05,0.14,0.30,6.5,0.30,2.7,3.2,36.0,0.43
22463,2023-01-31 23:55:00,1020.3,4.6,90.0,0.0,0.0,0.34,0.31,352.0,3.2,...,1.8,0.05,0.13,0.30,6.5,0.30,2.7,3.4,44.0,0.42

We translate the names of the columns.

In [27]:
#Dictionary of translations
translations_dic = {'Data': 'date',
 'Palazzo Cavalli Pressione_x': 'cavalli_atmospheric_pressure',
 'Palazzo Cavalli Temperatura_x': 'cavalli_air_temperature',
 "Palazzo Cavalli Umidita'_x": 'cavalli_relative_humidity',
 'Palazzo Cavalli Radiazione solare': 'cavalli_solar_radiation',
 'Palazzo Cavalli Pioggia 5m': 'cavalli_precipitation',
 'Burano Liv.Idrom. medio 1m': 'burano_sea_level',
 'Piattaforma CNR Liv.Idrom. medio 1m': 'ismar1_average_sea_level',
 'Piattaforma CNR D.Vento med. 10m': 'ismar1_average_wind_direction',
 'Piattaforma CNR V.Vento med.10m': 'ismar1_average_wind_speed',
 'Piattaforma CNR V.Vento max': 'ismar1_maximum_wind_speed',
 'Piattaforma CNR Onda: Alt. sign.': 'ismar1_significant_wave_height',
 'Piattaforma CNR Onda: Alt. max': 'ismar1_highest_wave_height',
 'Piattaforma CNR Pressione': 'ismar1_atmospheric_pressure',
 'Piattaforma CNR Temperatura': 'ismar1_air_temperature',
 'Piattaforma CNR Temp. Acqua': 'ismar1_water_temperature',
 "Piattaforma CNR Umidita'": 'ismar1_relative_humidity',
 'Piattaforma CNR Radiazione solare': 'ismar1_solar_radiation',
 'Piattaforma CNR Pioggia 5m_x': 'ismar1_precipitation',
 'Piattaforma CNR Pioggia 5m_y': 'ismar2_precipitation',
 'San Giorgio D.Vento med. 10m_x': 'san_giorgio_average_wind_direction',
 'San Giorgio V.Vento med.10m_x': 'san_giorgio_average_wind_speed',
 'San Giorgio V.Vento max_x': 'san_giorgio_maximum_wind_speed',
 'San Giorgio Temperatura': 'san_giorgio_air_temperature',
 "San Giorgio Umidita'": 'san_giorgio_relative_humidity',
 'San Giorgio Radiazione solare_x': 'san_giorgio_solar_radiation',
 'Misericordia Liv.Idrom. medio 1m': 'miser_average_sea_level',
 'Misericordia D.Vento med. 10m': 'miser_average_wind_direction',
 'Misericordia V.Vento med.10m': 'miser_average_wind_speed',
 'Misericordia V.Vento max': 'miser_maximum_wind_speed',
 'Misericordia Onda: Alt. sign.': 'miser_significant_wave_height',
 'Misericordia Onda: Alt. max': 'miser_highest_wave_height',
 'P. Salute Liv.Idrom. medio 1m': 'salute_average_sea_level',
 'P. Salute Temp. Acqua_x': 'salute_water_temperature',
 'D.S. Lido Liv.Idrom. medio 1m': 'faro_average_sea_level',
 'Faro Diga Lido V.Vento med.10m': 'faro_average_wind_speed',
 'Faro Diga Lido V.Vento max': 'faro_maximum_wind_speed',
 'Faro Diga Lido D.Vento med. 10m': 'faro_average_wind_direction',
 'valore': 'astro_tide'}

In [28]:
#Translating the names of the columns
venice.rename(columns=translations_dic, inplace=True)
venice.columns

Index(['date', 'cavalli_atmospheric_pressure', 'cavalli_air_temperature',
       'cavalli_relative_humidity', 'cavalli_solar_radiation',
       'cavalli_precipitation', 'burano_sea_level', 'ismar1_average_sea_level',
       'ismar1_average_wind_direction', 'ismar1_average_wind_speed',
       'ismar1_maximum_wind_speed', 'ismar1_significant_wave_height',
       'ismar1_highest_wave_height', 'ismar1_atmospheric_pressure',
       'ismar1_air_temperature', 'ismar1_water_temperature',
       'ismar1_relative_humidity', 'ismar1_solar_radiation',
       'ismar1_precipitation', 'ismar2_precipitation',
       'san_giorgio_average_wind_direction', 'san_giorgio_average_wind_speed',
       'san_giorgio_maximum_wind_speed', 'san_giorgio_air_temperature',
       'san_giorgio_relative_humidity', 'san_giorgio_solar_radiation',
       'miser_average_sea_level', 'miser_average_wind_direction',
       'miser_average_wind_speed', 'miser_maximum_wind_speed',
       'miser_significant_wave_height', 'miser_highest_wave_height',
       'salute_average_sea_level', 'salute_water_temperature',
       'faro_average_sea_level', 'faro_average_wind_speed',
       'faro_maximum_wind_speed', 'faro_average_wind_direction', 'astro_tide'],
      dtype='object')

We hourly aggregate observations following these rules:
1. Observations already reported as an average, are aggregated using the mean.
2. Observations reported using the maximum, are aggregated using the max.
3. Observations about precipitations are aggregated using a sum.
4. All other observations are aggregated using the median.
5. In all of the above aggregation methods, missing values are not taken into consideration.

In [29]:
venice=venice.resample('H', on='date').agg({'cavalli_atmospheric_pressure':'median', 'cavalli_air_temperature':'median',
                                     'cavalli_relative_humidity':'median','cavalli_solar_radiation':'median',
                                     'cavalli_precipitation':'sum','burano_sea_level':'mean','ismar1_average_sea_level':'mean', 
                                     'ismar1_average_wind_direction':'mean','ismar1_average_wind_speed':'mean', 
                                     'ismar1_maximum_wind_speed':'max','ismar1_significant_wave_height':'mean', 
                                     'ismar1_highest_wave_height':'max','ismar1_atmospheric_pressure':'median', 
                                     'ismar1_air_temperature':'median','ismar1_water_temperature':'median', 
                                     'ismar1_relative_humidity': 'median','ismar1_solar_radiation':'median', 
                                     'ismar1_precipitation':'sum','ismar2_precipitation':'sum', 
                                     'san_giorgio_average_wind_direction':'mean','san_giorgio_average_wind_speed':'mean', 
                                     'san_giorgio_maximum_wind_speed':'max','san_giorgio_air_temperature':'median', 
                                     'san_giorgio_relative_humidity':'median','san_giorgio_solar_radiation':'median', 
                                     'miser_average_sea_level':'mean','miser_average_wind_direction':'mean', 
                                     'miser_average_wind_speed':'mean','miser_maximum_wind_speed':'max', 
                                     'miser_significant_wave_height':'mean','miser_highest_wave_height':'max', 
                                     'salute_average_sea_level':'mean','salute_water_temperature':'median', 
                                     'faro_average_sea_level':'mean','faro_average_wind_speed':'mean', 
                                     'faro_maximum_wind_speed':'max','faro_average_wind_direction':'mean', 
                                     'astro_tide':'mean'}).reset_index()
venice

,date,cavalli_atmospheric_pressure,cavalli_air_temperature,cavalli_relative_humidity,cavalli_solar_radiation,cavalli_precipitation,burano_sea_level,ismar1_average_sea_level,ismar1_average_wind_direction,ismar1_average_wind_speed,...,miser_maximum_wind_speed,miser_significant_wave_height,miser_highest_wave_height,salute_average_sea_level,salute_water_temperature,faro_average_sea_level,faro_average_wind_speed,faro_maximum_wind_speed,faro_average_wind_direction,astro_tide
0,2022-11-15 00:00:00,1018.90,11.90,88.0,0.0,0.0,0.290833,0.365833,278.166667,5.491667,...,4.5,0.050000,0.20,0.342500,15.5,0.394167,4.041667,7.2,278.833333,0.245833
1,2022-11-15 01:00:00,1018.35,11.30,89.0,0.0,0.0,0.370000,0.410833,283.500000,4.541667,...,3.2,0.034167,0.15,0.410833,15.4,0.445000,3.733333,5.7,283.416667,0.319167
2,2022-11-15 02:00:00,1018.00,11.20,90.0,0.0,0.0,0.426667,0.438333,280.916667,4.100000,...,3.1,0.040833,0.17,0.453333,15.3,0.470000,2.975000,4.9,273.083333,0.377500
3,2022-11-15 03:00:00,1017.80,10.20,92.0,0.0,0.0,0.470000,0.460833,260.333333,6.383333,...,4.6,0.050000,0.21,0.485833,15.3,0.492500,5.141667,7.6,258.916667,0.417500
4,2022-11-15 04:00:00,1017.35,9.90,92.5,0.0,0.0,0.493333,0.465833,272.416667,5.258333,...,3.2,0.094167,0.31,0.480833,15.3,0.498333,3.966667,6.1,284.000000,0.442500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,2023-01-31 19:00:00,1020.50,7.65,83.0,0.0,0.0,0.181667,0.348333,202.166667,4.083333,...,1.8,0.090000,0.30,0.287500,6.6,0.341667,3.083333,3.9,192.083333,0.335000
1868,2023-01-31 20:00:00,1020.40,7.10,84.5,0.0,0.0,0.274167,0.389167,229.416667,4.750000,...,3.1,0.103333,0.32,0.354167,6.7,0.380833,3.225000,4.5,246.916667,0.400833
1869,2023-01-31 21:00:00,1020.70,5.80,87.0,0.0,0.0,0.343333,0.401667,271.250000,3.083333,...,3.8,0.082500,0.31,0.392500,6.5,0.393333,2.416667,4.4,89.916667,0.437500
1870,2023-01-31 22:00:00,1020.35,5.90,89.0,0.0,0.0,0.370833,0.368333,243.250000,3.316667,...,3.7,0.065833,0.22,0.395833,6.5,0.365833,1.575000,2.7,146.500000,0.447500
1871,2023-01-31 23:00:00,1020.50,4.80,88.5,0.0,0.0,0.361667,0.329167,302.416667,3.541667,...,4.0,0.073333,0.27,0.339167,6.5,0.324167,3.466667,6.1,80.166667,0.433333

The column ismar2_precipitation should exactly reflect the cumulative precipitations observed at the ISMAR-CNR Platform as the documentation suggests. However, with the code below, we see that our cumulative aggregation of 'ismar1_precipitation' differs from the 'ismar2_precipitation'.\
For this reason we keep both columns.

In [30]:
venice.resample('H',on='date').sum()['ismar1_precipitation'].equals(venice.resample('H',on='date').sum()['ismar2_precipitation'])

False

Exporting the tidy dataset to a csv file.

In [31]:
venice.to_csv("tidy_dataset_group_12.csv",index=False)

## Documentation

|Variable|Description|
|--------|-----------|
|date|Hourly observations from 2022-11-15 00:00:00 to 2023-01-31 23:55:00|
|cavalli_atmospheric_pressure|Atmospheric pressure measured in hPa from methereological station Cavalli|
|cavalli_air_temperature|Air temperature measured in °C from methereological station Cavalli|
|cavalli_relative_humidity| Relative umidity measured in % from methereological station Cavalli|
|cavalli_solar_radiation| Solar Radiation measured in W/m2 from methereological station Cavalli|
|cavalli_precipitation| Precipitation in mm from methereological station Cavalli|
|burano_sea_level| Average sea level in meters above ZMPS on the minute before the observation from methereological station Burano|
|ismar1_average_sea_level|Average sea level in meters (on the minute before the observation) from the platform ISMAR-CNR|
|ismar1_average_wind_direction| Average wind direction (on the 10 minutes before the observation) in degrees from the platform ISMAR-CNR|
|ismar1_average_wind_speed| Average wind speed (on the 10 minutes before the observation) in m/s from the platform ISMAR-CNR|
|ismar1_maximum_wind_speed| Maximum wind speed (on the 15 minutes before the observation) in m/s from the platform ISMAR-CNR|
|ismar1_significant_wave_height| Height of significant wave (mean of the highest third of all the waves) in meters from platform ISMAR-CNR|
|ismar1_highest_wave_height| Height of the highest wave in meters from platform ISMAR-CNR|
|ismar1_atmospheric_pressure| Atmospheric pressure mesured in hPa from platform ISMAR-CNR|
|ismar1_air_temperature|Air temperature measured in °C from platform ISMAR-CNR|
|ismar1_water_temperature| Water temperature measured in °C from platform ISMAR-CNR|
|ismar1_relative_humidity|Relative umidity measured in % from platform ISMAR-CNR|
|ismar1_solar_radiation| Solar Radiation measured in W/m2 from platform ISMAR-CNR|
|ismar1_precipitation| Precipitation in mm from platform ISMAR-CNR|
|ismar2_precipitation|Cumulative precipitation in mm from platform ISMAR-CNR|
|san_giorgio_average_wind_direction| Average wind direction (on the 10 minutes before the observation) in degrees from the methereological station San Giorgio|
|san_giorgio_average_wind_speed| Average wind speed (on the 10 minutes before the observation)in degrees from the methereological station San Giorgio|
|san_giorgio_maximum_wind_speed|Maximum wind speed (on the 15 minutes before the observation) in m/s from the methereological station San Giorgio|
|san_giorgio_air_temperature|Air temperature measured in °C from the methereological station San Giorgio|
|san_giorgio_relative_humidity|Relative umidity measured in % from the methereological station San Giorgio|
|san_giorgio_solar_radiation|Solar Radiation measured in W/m2 from the methereological station San Giorgio|
|miser_average_sea_level|Average sea level in meters (on the minute before the observation) from the methereological station Misericordia|
|miser_average_wind_direction| Average wind direction (on the 10 minutes before the observation) in degrees from the methereological station Misericordia|
|miser_average_wind_speed| Average wind speed (on the 10 minutes before the observation)in degrees from the methereological station Misericordia|
|miser_maximum_wind_speed|Maximum wind speed (on the 15 minutes before the observation) in m/s from the methereological station Misericordia|
|miser_significant_wave_height|Height of significant wave (mean of the highest third of all the waves) in meters from the methereologial station Misericordia|
|miser_highest_wave_height|Height of the highest wave in meters from the methereological station Misericordia|
|salute_average_sea_level|Average sea level in meters (on the minute before the observation) from the methereological station Punta Salute Canal Grande|
|salute_water_temperature| Water temperature measured in °C from the methereological station Punta Salute Canal Grande|
|faro_average_sea_level|Average sea level in meters (on the minute before the observation) from the methereological station Diga Sud Lido |
|faro_average_wind_speed| Average wind speed (on the 10 minutes before the observation) in m/s from the methereological station Diga Sud Lido |
|faro_maximum_wind_speed| Maximum wind speed (on the 15 minutes before the observation) in m/s from the methereological station Diga Sud Lido |
|faro_average_wind_direction| Average wind direction (on the 10 minutes before the observation) in degrees from the methereological station Diga Sud Lido|
|astro_tide| Astronomical tide caused by the gravitational attraction that the heavenly bodies, mainly the Moon and Sun, have on the body of water|

Notice that each variable has been aggregated on an hourly basis using appropiate aggregation methods, as reported in the code above.